In [70]:
# Libraries.
import pandas as pd
from scipy import stats

In [71]:
randomGenesDF = pd.read_csv("/Users/andrewhsu/Projects/McNair/data/randomGenesTable.csv")
orthoTable = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/orthologTableDistDupeBioTypeParentalDaughterGOEPExondNdSProtID.parquet")
humanParentDaughter = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/humanParentDaughter.parquet")
mouseParentDaughter = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/mouseParentDaughter.parquet")
parentDaughterDFs = {"Human": humanParentDaughter, "Mouse": mouseParentDaughter}

orthoTable = orthoTable[(orthoTable["Human Gene Type"] == "protein_coding") & (orthoTable["Mouse Gene Type"] == "protein_coding")]
orthoTableNoRetro = orthoTable[((orthoTable["Number of Human Exons"] != 1) | (orthoTable["Number of Mouse Exons"] != 1))]
orthoTableNoOverUnderRepresentation = orthoTable[orthoTable["+/-"] == "nan"]
display(orthoTable)

,Gene stable ID,Mouse gene stable ID,Mouse homology type,Mouse Gene-order conservation score,EuclidDist,EuclidDistNorm,EuclidDistLog,PearDist,TEC,Num Human Dupes,...,Mouse Pancreas,Mouse Stomach,Human Exon stable ID,Mouse Exon stable ID,Number of Human Exons,Number of Mouse Exons,dN/dS,dN,dS,% Protein Identity
0,ENSG00000065135,ENSMUSG00000000001,ortholog_one2one,100.0,197.746445,0.278561,6.701999,0.151442,0.000000,1.0,...,8.901608,54.003405,"ENSE00001451089, ENSE00001781395, ENSE00000783...","ENSMUSE00000565001, ENSMUSE00000565003, ENSMUS...",21,9,0.02836,0.0079,0.2774,98.305085
1,ENSG00000093009,ENSMUSG00000000028,ortholog_one2one,100.0,24.533616,1.024816,5.058507,1.001638,0.250000,1.0,...,0.181636,3.491172,"ENSE00001792680, ENSE00003648368, ENSE00003550...","ENSMUSE00000645082, ENSMUSE00000645087, ENSMUS...",73,25,0.08039,0.0414,0.5152,91.696113
2,ENSG00000102098,ENSMUSG00000000037,ortholog_one2one,100.0,2.084639,0.471628,1.444542,0.161786,0.166667,1.0,...,0.000000,0.287549,"ENSE00001341544, ENSE00002285630, ENSE00001740...","ENSMUSE00001467377, ENSMUSE00001463955, ENSMUS...",30,50,0.34796,0.2351,0.6757,66.666667
3,ENSG00000091583,ENSMUSG00000000049,ortholog_one2one,100.0,1776.546401,0.002316,2.516381,0.000003,0.500000,1.0,...,0.686123,0.319685,"ENSE00002728335, ENSE00003463428, ENSE00000742...","ENSMUSE00000413982, ENSMUSE00000108745, ENSMUS...",45,16,0.22115,0.1518,0.6863,76.521739
4,ENSG00000141562,ENSMUSG00000000056,ortholog_one2one,100.0,70.950296,0.525139,3.511421,0.661562,0.000000,1.0,...,1.971657,21.775717,"ENSE00002706239, ENSE00003507751, ENSE00003559...","ENSMUSE00000333527, ENSMUSE00000134384, ENSMUS...",90,16,0.12193,0.0844,0.6925,85.526316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22117,ENSG00000182854,ENSMUSG00000109528,ortholog_one2one,50.0,0.007129,NaN,0.009994,NaN,NaN,1.0,...,0.000000,0.000000,"ENSE00003814070, ENSE00001310389","ENSMUSE00001404751, ENSMUSE00001396123, ENSMUS...",2,13,0.14733,0.0866,0.5876,85.576923
22118,ENSG00000183303,ENSMUSG00000109542,ortholog_one2many,75.0,0.025535,NaN,0.020456,NaN,NaN,1.0,...,0.000000,0.000000,ENSE00001324685,"ENSMUSE00001406325, ENSMUSE00001411928, ENSMUS...",1,6,0.32230,0.1593,0.4943,73.615635
22119,ENSG00000145700,ENSMUSG00000109561,ortholog_one2one,100.0,0.362324,1.136140,0.434832,1.194783,NaN,1.0,...,0.000000,0.000000,"ENSE00002051371, ENSE00003552443, ENSE00003670...","ENSMUSE00001376463, ENSMUSE00001380455, ENSMUS...",50,35,0.57196,0.2960,0.5175,58.138207
22120,ENSG00000181143,ENSMUSG00000109564,ortholog_one2one,75.0,11.742337,0.616651,3.766970,0.237058,NaN,1.0,...,0.338525,1.011829,"ENSE00001432158, ENSE00001433823, ENSE00001422...","ENSMUSE00001381494, ENSMUSE00001381664, ENSMUS...",105,90,0.44482,0.5519,1.2407,47.573363
22121,ENSG00000206113,ENSMUSG00000109572,ortholog_one2one,100.0,0.733072,0.652040,0.825684,0.284662,NaN,1.0,...,0.000000,0.012197,"ENSE00001493543, ENSE00003738843, ENSE00003796...","ENSMUSE00001381090, ENSMUSE00001379845, ENSMUS...",32,16,0.16672,0.1680,1.0078,72.910217

In [72]:
randomGenesDF["Number of Human Exons"] = randomGenesDF["HumanID"].map(orthoTable.set_index("Gene stable ID")["Number of Human Exons"].to_dict())
randomGenesDF["Number of Mouse Exons"] = randomGenesDF["MouseID"].map(orthoTable.set_index("Mouse gene stable ID")["Number of Mouse Exons"].to_dict())
randomGenesDF["Human +/-"] = randomGenesDF["HumanID"].map(orthoTable.set_index("Gene stable ID")["+/-"].to_dict())
randomGenesDF["Mouse +/-"] = randomGenesDF["MouseID"].map(orthoTable.set_index("Mouse gene stable ID")["+/-"].to_dict())

randomGenesNoRetro = randomGenesDF[((randomGenesDF["Number of Human Exons"] != 1) | (randomGenesDF["Number of Mouse Exons"] != 1))]
randomGenesNoOverUnderRepresentation = randomGenesDF[(randomGenesDF["Human +/-"] == "nan") & (randomGenesDF["Mouse +/-"] == "nan")]
display(randomGenesDF)

,HumanID,MouseID,EuclidDist,EuclidDistNorm,EuclidDistLog,PearDist,TEC,Number of Human Exons,Number of Mouse Exons,Human +/-,Mouse +/-
0,ENSG00000000971,ENSMUSG00000000049,1648.502447,0.322558,9.334532,0.032440,0.250,NaN,16.0,NaN,nan
1,ENSG00000001036,ENSMUSG00000000056,71.067645,0.697079,3.998596,1.349007,0.000,32.0,16.0,nan,nan
2,ENSG00000001084,ENSMUSG00000000078,152.010822,0.680316,5.442806,0.618386,0.000,60.0,11.0,+,nan
3,ENSG00000001167,ENSMUSG00000000088,2119.855406,0.565457,16.948433,1.150569,0.000,73.0,11.0,-,nan
4,ENSG00000001561,ENSMUSG00000000094,28.852232,0.976974,8.429828,0.742289,0.375,12.0,13.0,nan,-
...,...,...,...,...,...,...,...,...,...,...,...
9995,ENSG00000293663,ENSMUSG00000109516,0.042077,NaN,0.060123,NaN,NaN,1.0,NaN,nan,NaN
9996,ENSG00000293689,ENSMUSG00000109520,0.355014,NaN,0.476970,NaN,NaN,NaN,3.0,NaN,+
9997,ENSG00000300293,ENSMUSG00000109528,0.068948,NaN,0.096257,NaN,NaN,NaN,13.0,NaN,+
9998,ENSG00000300510,ENSMUSG00000109542,1.096681,NaN,1.230796,NaN,NaN,10.0,6.0,nan,+
9999,ENSG00000310517,ENSMUSG00000109544,145.951064,NaN,14.834910,NaN,NaN,213.0,NaN,nan,NaN

In [73]:
headerCols = ["n", "Median", "Mean", "Rho", "Corr PValue"]
statsDF = pd.DataFrame(
    index = ["one-to-one", "one-to-many",
                "one-to-many, duplicated in human", 
                "one-to-many, duplicated in human, GOC=0", "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=100",
                "one-to-many, duplicated in mouse",
                "one-to-many, duplicated in mouse, GOC=0", "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=100",
                "many-to-many", "random",
                "trios, duplicated in human, parental", "trios, duplicated in human, daughter",
                "trios, duplicated in mouse, parental", "trios, duplicated in mouse, daughter"],
    columns=headerCols
)

In [74]:
sigDF = pd.DataFrame({
    "Group 1": ["one-to-one", "one-to-one",
                "one-to-many, duplicated in human",
                "many-to-many", "many-to-many",
                "one-to-many, duplicated in human, GOC=0", "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=0",
                "one-to-many, duplicated in mouse, GOC=0", "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=0",
                "trios, duplicated in human, parental", "trios, duplicated in mouse, parental"],

    "Group 2": ["one-to-many, duplicated in human", "one-to-many, duplicated in mouse",
                "one-to-many, duplicated in mouse", 
                "one-to-many, duplicated in human", "one-to-many, duplicated in mouse", 
                "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=100", "one-to-many, duplicated in human, GOC=100",
                "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=100", "one-to-many, duplicated in mouse, GOC=100",
                "trios, duplicated in human, daughter", "trios, duplicated in mouse, daughter"],
    "P-value": 0.0
})

In [75]:
translationTable = {
    "one-to-one": "ortholog_one2one",
    "one-to-many": "ortholog_one2many",
    "duplicated in human": "Human",
    "duplicated in mouse": "Mouse",
    "GOC=0": 0,
    "GOC=25": 25,
    "GOC=50": 50,
    "GOC=75": 75,
    "GOC=100": 100,
    "many-to-many": "ortholog_many2many",
    "random": "random",
    "trios": "ortholog_one2many",
    "duplicated in human": "Human",
    "duplicated in mouse": "Mouse",
    "parental": "Parent",
    "daughter": "Daughter"
}

In [76]:
randomGenesList = [randomGenesDF, randomGenesNoRetro, randomGenesNoOverUnderRepresentation]
dfValuesList = []
for idx, df in enumerate([orthoTable, orthoTableNoRetro, orthoTableNoOverUnderRepresentation]):
    dfValues = statsDF.to_dict(orient="index")
    for distMetric in df.columns[4:9]:
        for category in statsDF.index:
            translatedCategory = list(map(translationTable.get, category.split(", ")))
            if "random" in translatedCategory:
                filteredDF = randomGenesList[idx]
            elif len(translatedCategory) == 1:
                filteredDF = df[df["Mouse homology type"] == translatedCategory[0]]
            elif len(translatedCategory) == 2:
                filteredDF = df[(df["Mouse homology type"] == translatedCategory[0]) & (df["Duplicated Species"] == translatedCategory[1])]
            elif len(translatedCategory) == 3 and isinstance(translatedCategory[2], int):
                filteredDF = df[(df["Mouse homology type"] == translatedCategory[0]) & (df["Duplicated Species"] == translatedCategory[1]) & (df["Mouse Gene-order conservation score"] == translatedCategory[2])]
            elif len(translatedCategory) == 3 and isinstance(translatedCategory[2], str):
                parentalDaughterDF = parentDaughterDFs[translatedCategory[1]]
                filteredDF = parentalDaughterDF.filter(like=translatedCategory[2])
                filteredDF.columns = filteredDF.columns.str.replace(f" {translatedCategory[2]}", "")
            for column in statsDF.columns:
                if column == "n":
                    dfValues[category][column] = filteredDF[distMetric].dropna().shape[0]
                elif column == "Median":
                    dfValues[category][column] = filteredDF[distMetric].dropna().median()
                elif column == "Mean":
                    dfValues[category][column] = filteredDF[distMetric].dropna().mean()
                elif column == "Rho" and len(translatedCategory) > 1 and "one-to-many" in category:
                    filteredTissueNADF = filteredDF[(filteredDF[distMetric].notna()) & (filteredDF[f"Num {translatedCategory[1]} Dupes"].notna())]
                    dfValues[category][column] = stats.spearmanr(filteredTissueNADF[distMetric], filteredTissueNADF[f"Num {translatedCategory[1]} Dupes"]).statistic
                elif column == "Corr PValue" and len(translatedCategory) > 1 and "one-to-many" in category:
                    filteredTissueNADF = filteredDF[(filteredDF[distMetric].notna()) & (filteredDF[f"Num {translatedCategory[1]} Dupes"].notna())]
                    dfValues[category][column] = stats.spearmanr(filteredTissueNADF[distMetric], filteredTissueNADF[f"Num {translatedCategory[1]} Dupes"]).pvalue
        dfValuesList.append(pd.DataFrame(dfValues).T)

In [77]:
sigDFArr= []
for idx, df in enumerate([orthoTable, orthoTableNoRetro, orthoTableNoOverUnderRepresentation]):
    for distMetric in df.columns[4:9]:
        pValueArr = []
        for rowNum in range(sigDF.shape[0]):
            translatedGroup1 = list(map(translationTable.get, sigDF.iloc[rowNum, :].iloc[0].split(", ")))
            translatedGroup2 = list(map(translationTable.get, sigDF.iloc[rowNum, :].iloc[1].split(", ")))
            if len(translatedGroup1) == 1:
                filteredDF1 = df[df["Mouse homology type"] == translatedGroup1[0]]
            elif len(translatedGroup1) == 2:
                filteredDF1 = df[(df["Mouse homology type"] == translatedGroup1[0]) & (df["Duplicated Species"] == translatedGroup1[1])]
            elif len(translatedGroup1) == 3 and isinstance(translatedGroup1[2], int):
                filteredDF1 = df[(df["Mouse homology type"] == translatedGroup1[0]) & (df["Duplicated Species"] == translatedGroup1[1]) & (df["Mouse Gene-order conservation score"] == translatedGroup1[2])]
            elif len(translatedGroup1) == 3 and isinstance(translatedGroup1[2], str):
                parentalDaughterDF1 = parentDaughterDFs[translatedGroup1[1]]
                filteredDF1 = parentalDaughterDF1.filter(like=translatedGroup1[2])
                filteredDF1.columns = filteredDF1.columns.str.replace(f" {translatedGroup1[2]}", "")

            if len(translatedGroup2) == 1:
                filteredDF2 = df[df["Mouse homology type"] == translatedGroup2[0]]
            elif len(translatedGroup2) == 2:
                filteredDF2 = df[(df["Mouse homology type"] == translatedGroup2[0]) & (df["Duplicated Species"] == translatedGroup2[1])]
            elif len(translatedGroup2) == 3 and isinstance(translatedGroup2[2], int):
                filteredDF2 = df[(df["Mouse homology type"] == translatedGroup2[0]) & (df["Duplicated Species"] == translatedGroup2[1]) & (df["Mouse Gene-order conservation score"] == translatedGroup2[2])]
            elif len(translatedGroup2) == 3 and isinstance(translatedGroup2[2], str):
                parentalDaughterDF2 = parentDaughterDFs[translatedGroup2[1]]
                filteredDF2 = parentalDaughterDF2.filter(like=translatedGroup2[2])
                filteredDF2.columns = filteredDF2.columns.str.replace(f" {translatedGroup2[2]}", "")

            pValueArr.append(stats.mannwhitneyu(filteredDF1[distMetric].dropna(), filteredDF2[distMetric].dropna())[1])

        sigDF["P-value"] = pValueArr
        sigDFArr.append(sigDF.copy())

In [78]:
with pd.ExcelWriter("/Users/andrewhsu/Projects/McNair/data/analysisTable.xlsx") as w:
    for analysisTypeIdx in range(0, 3):
        for distMetricIdx, distMetric in enumerate(orthoTable.columns[4:9]):
            if analysisTypeIdx == 0:
                dfValuesList[analysisTypeIdx * 5 + distMetricIdx].to_excel(w, sheet_name=distMetric, startrow=1, index=True)
                sigDFArr[analysisTypeIdx * 5 + distMetricIdx].to_excel(w, sheet_name=distMetric, startrow=1, startcol=8, index=False)
            else:
                dfValuesList[analysisTypeIdx * 5 + distMetricIdx].to_excel(w, sheet_name=distMetric, startrow=(21 * analysisTypeIdx + 3 + (analysisTypeIdx - 1)), index=True, header=False)
                sigDFArr[analysisTypeIdx * 5 + distMetricIdx].to_excel(w, sheet_name=distMetric, startrow=(21 * analysisTypeIdx + 3 + (analysisTypeIdx - 1)), startcol=8, index=False, header=False)

                sheet = w.sheets[distMetric]
                sheet.cell(row=24, column=1, value="Retrogenes Removed")
                sheet.cell(row=46, column=1, value="Under/Overrepresentation Removed")
                sheet.cell(row=1, column=1, value="Standard")
                sheet.cell(row=2, column=1, value="Category")