In [1]:
# Libraries.
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
orthoTable = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/orthologTableDistDupeBioTypeParentalDaughterGOEPExondNdSProtID.parquet")
randomGenesDF = pd.read_csv("/Users/andrewhsu/Projects/McNair/data/randomGenesTable.csv")
humanParentDaughter = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/humanParentDaughter.parquet")
mouseParentDaughter = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/mouseParentDaughter.parquet")

orthoTable = orthoTable[(orthoTable["Human Gene Type"] == "protein_coding") & (orthoTable["Mouse Gene Type"] == "protein_coding")]
orthoTableNoRetro = orthoTable[((orthoTable["Number of Human Exons"] != 1) | (orthoTable["Number of Mouse Exons"] != 1))]
orthoTableNoOverUnderRepresentation = orthoTable[orthoTable["+/-"] == "nan"]
display(orthoTable)

humanParentDaughter = humanParentDaughter.merge(orthoTable[["Gene stable ID", "Mouse gene stable ID", "+/-", "Number of Human Exons", "dN", "dS", "dN/dS"]], left_on=["Mouse Gene", "Human Parent"], right_on=["Mouse gene stable ID", "Gene stable ID"], how="left").drop(columns=["Gene stable ID", "Mouse gene stable ID"]).rename(columns={"Number of Human Exons": "Number of Parental Exons", "+/-": "Parent +/-", "dN": "dN Parent", "dS": "dS Parent", "dN/dS": "dN/dS Parent"})
humanParentDaughter = humanParentDaughter.merge(orthoTable[["Gene stable ID", "Mouse gene stable ID", "+/-", "Number of Human Exons", "dN", "dS", "dN/dS"]], left_on=["Mouse Gene", "Human Daughter"], right_on=["Mouse gene stable ID", "Gene stable ID"], how="left").drop(columns=["Gene stable ID", "Mouse gene stable ID"]).rename(columns={"Number of Human Exons": "Number of Daughter Exons", "+/-": "Daughter +/-", "dN": "dN Daughter", "dS": "dS Daughter", "dN/dS": "dN/dS Daughter"})
mouseParentDaughter = mouseParentDaughter.merge(orthoTable[["Gene stable ID", "Mouse gene stable ID", "+/-", "Number of Mouse Exons", "dN", "dS", "dN/dS"]], left_on=["Human Gene", "Mouse Parent"], right_on=["Gene stable ID", "Mouse gene stable ID"], how="left").drop(columns=["Gene stable ID", "Mouse gene stable ID"]).rename(columns={"Number of Mouse Exons": "Number of Parental Exons", "+/-": "Parent +/-", "dN": "dN Parent", "dS": "dS Parent", "dN/dS": "dN/dS Parent"})
mouseParentDaughter = mouseParentDaughter.merge(orthoTable[["Gene stable ID", "Mouse gene stable ID", "+/-", "Number of Mouse Exons", "dN", "dS", "dN/dS"]], left_on=["Human Gene", "Mouse Daughter"], right_on=["Gene stable ID", "Mouse gene stable ID"], how="left").drop(columns=["Gene stable ID", "Mouse gene stable ID"]).rename(columns={"Number of Mouse Exons": "Number of Daughter Exons", "+/-": "Daughter +/-", "dN": "dN Daughter", "dS": "dS Daughter", "dN/dS": "dN/dS Daughter"})


humanParentDaughterNoRetro = humanParentDaughter[(humanParentDaughter["Number of Parental Exons"] != 1) | (humanParentDaughter["Number of Daughter Exons"] != 1)]
humanParentDaughterNoOverUnderRepresentation = humanParentDaughter[(humanParentDaughter["Parent +/-"] != "nan") | (humanParentDaughter["Daughter +/-"] == "nan")]
mouseParentDaughterNoRetro = mouseParentDaughter[(mouseParentDaughter["Number of Parental Exons"] != 1) | (mouseParentDaughter["Number of Daughter Exons"] != 1)]
mouseParentDaughterNoOverUnderRepresentation = mouseParentDaughter[(mouseParentDaughter["Parent +/-"] != "nan") | (mouseParentDaughter["Daughter +/-"] == "nan")]

parentDaughterDFs = {"Human": [humanParentDaughter, humanParentDaughterNoRetro, humanParentDaughterNoOverUnderRepresentation], "Mouse": [mouseParentDaughter, mouseParentDaughterNoRetro, mouseParentDaughterNoOverUnderRepresentation]}
display(humanParentDaughter)

randomGenesDF = randomGenesDF.merge(orthoTable[["Gene stable ID", "+/-", "Number of Human Exons", "dN", "dS", "dN/dS"]], left_on="HumanID", right_on="Gene stable ID", how="left").drop(columns=["Gene stable ID"]).rename(columns={"+/-": "Human +/-", "dN": "Human dN", "dS": "Human dS", "dN/dS": "Human dN/dS"})
randomGenesDF = randomGenesDF.merge(orthoTable[["Mouse gene stable ID", "+/-", "Number of Mouse Exons", "dN", "dS", "dN/dS"]], left_on="MouseID", right_on="Mouse gene stable ID", how="left").drop(columns=["Mouse gene stable ID"]).rename(columns={"+/-": "Mouse +/-", "dN": "Mouse dN", "dS": "Mouse dS", "dN/dS": "Mouse dN/dS"})

randomGenesNoRetro = randomGenesDF[((randomGenesDF["Number of Human Exons"] != 1) | (randomGenesDF["Number of Mouse Exons"] != 1))]
randomGenesNoOverUnderRepresentation = randomGenesDF[(randomGenesDF["Human +/-"] == "nan") & (randomGenesDF["Mouse +/-"] == "nan")]
display(randomGenesDF)

,Gene stable ID,Mouse gene stable ID,Mouse homology type,Mouse Gene-order conservation score,EuclidDist,EuclidDistNorm,EuclidDistLog,PearDist,TEC,Num Human Dupes,...,Mouse Pancreas,Mouse Stomach,Human Exon stable ID,Mouse Exon stable ID,Number of Human Exons,Number of Mouse Exons,dN/dS,dN,dS,% Protein Identity
0,ENSG00000065135,ENSMUSG00000000001,ortholog_one2one,100.0,197.746445,0.278561,6.701999,0.151442,0.000000,1.0,...,8.901608,54.003405,"ENSE00001451089, ENSE00001781395, ENSE00000783...","ENSMUSE00000565001, ENSMUSE00000565003, ENSMUS...",21,9,0.02836,0.0079,0.2774,98.305085
1,ENSG00000093009,ENSMUSG00000000028,ortholog_one2one,100.0,24.533616,1.024816,5.058507,1.001638,0.250000,1.0,...,0.181636,3.491172,"ENSE00001792680, ENSE00003648368, ENSE00003550...","ENSMUSE00000645082, ENSMUSE00000645087, ENSMUS...",73,25,0.08039,0.0414,0.5152,91.696113
2,ENSG00000102098,ENSMUSG00000000037,ortholog_one2one,100.0,2.084639,0.471628,1.444542,0.161786,0.166667,1.0,...,0.000000,0.287549,"ENSE00001341544, ENSE00002285630, ENSE00001740...","ENSMUSE00001467377, ENSMUSE00001463955, ENSMUS...",30,50,0.34796,0.2351,0.6757,66.666667
3,ENSG00000091583,ENSMUSG00000000049,ortholog_one2one,100.0,1776.546401,0.002316,2.516381,0.000003,0.500000,1.0,...,0.686123,0.319685,"ENSE00002728335, ENSE00003463428, ENSE00000742...","ENSMUSE00000413982, ENSMUSE00000108745, ENSMUS...",45,16,0.22115,0.1518,0.6863,76.521739
4,ENSG00000141562,ENSMUSG00000000056,ortholog_one2one,100.0,70.950296,0.525139,3.511421,0.661562,0.000000,1.0,...,1.971657,21.775717,"ENSE00002706239, ENSE00003507751, ENSE00003559...","ENSMUSE00000333527, ENSMUSE00000134384, ENSMUS...",90,16,0.12193,0.0844,0.6925,85.526316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22117,ENSG00000182854,ENSMUSG00000109528,ortholog_one2one,50.0,0.007129,NaN,0.009994,NaN,NaN,1.0,...,0.000000,0.000000,"ENSE00003814070, ENSE00001310389","ENSMUSE00001404751, ENSMUSE00001396123, ENSMUS...",2,13,0.14733,0.0866,0.5876,85.576923
22118,ENSG00000183303,ENSMUSG00000109542,ortholog_one2many,75.0,0.025535,NaN,0.020456,NaN,NaN,1.0,...,0.000000,0.000000,ENSE00001324685,"ENSMUSE00001406325, ENSMUSE00001411928, ENSMUS...",1,6,0.32230,0.1593,0.4943,73.615635
22119,ENSG00000145700,ENSMUSG00000109561,ortholog_one2one,100.0,0.362324,1.136140,0.434832,1.194783,NaN,1.0,...,0.000000,0.000000,"ENSE00002051371, ENSE00003552443, ENSE00003670...","ENSMUSE00001376463, ENSMUSE00001380455, ENSMUS...",50,35,0.57196,0.2960,0.5175,58.138207
22120,ENSG00000181143,ENSMUSG00000109564,ortholog_one2one,75.0,11.742337,0.616651,3.766970,0.237058,NaN,1.0,...,0.338525,1.011829,"ENSE00001432158, ENSE00001433823, ENSE00001422...","ENSMUSE00001381494, ENSMUSE00001381664, ENSMUS...",105,90,0.44482,0.5519,1.2407,47.573363
22121,ENSG00000206113,ENSMUSG00000109572,ortholog_one2one,100.0,0.733072,0.652040,0.825684,0.284662,NaN,1.0,...,0.000000,0.012197,"ENSE00001493543, ENSE00003738843, ENSE00003796...","ENSMUSE00001381090, ENSMUSE00001379845, ENSMUS...",32,16,0.16672,0.1680,1.0078,72.910217

,Mouse Gene,Human Parent,Human Daughter,GOC Parent,GOC Daughter,EuclidDist Parent,EuclidDist Daughter,EuclidDistNorm Parent,EuclidDistNorm Daughter,EuclidDistLog Parent,...,Parent +/-,Number of Parental Exons,dN Parent,dS Parent,dN/dS Parent,Daughter +/-,Number of Daughter Exons,dN Daughter,dS Daughter,dN/dS Daughter
0,ENSMUSG00000000308,ENSG00000237289,ENSG00000223572,100.0,75.0,2561.844409,2569.930198,1.182314,0.869675,11.026921,...,nan,60,0.0158,0.2890,0.05482,nan,53,0.0158,0.2896,0.05467
1,ENSMUSG00000000804,ENSG00000170832,ENSG00000129204,50.0,0.0,94.660307,115.484260,0.495699,0.769929,4.109197,...,nan,67,0.0206,0.3557,0.05794,nan,67,0.1968,0.7669,0.25661
2,ENSMUSG00000000982,ENSG00000277632,ENSG00000275385,25.0,0.0,9.978136,10.376588,0.789561,1.049001,4.253360,...,"+, +",7,0.1610,0.7459,0.21583,"+, +",5,0.3471,0.6263,0.55423
3,ENSMUSG00000001157,ENSG00000087338,ENSG00000244234,100.0,0.0,43.865728,60.650177,0.472288,0.727488,4.197032,...,nan,39,0.0363,0.5008,0.07246,nan,1,0.0798,0.5450,0.14636
4,ENSMUSG00000002546,ENSG00000167110,ENSG00000232653,75.0,0.0,60.192802,129.935081,0.436744,0.736270,3.662404,...,+,92,0.1379,0.9455,0.14585,+,38,0.5753,1.7270,0.33310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,ENSMUSG00000102976,ENSG00000058673,ENSG00000214558,100.0,0.0,292.704208,292.634675,0.555819,0.478797,13.873760,...,nan,66,0.1132,0.4879,0.23193,nan,2,0.1400,0.5018,0.27894
123,ENSMUSG00000103707,ENSG00000081842,ENSG00000204962,75.0,50.0,2.791802,3.229265,0.456832,0.289487,1.416028,...,-,7,0.0798,0.6394,0.12477,-,5,0.1015,0.6788,0.14961
124,ENSMUSG00000116652,ENSG00000286025,ENSG00000286102,25.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
125,ENSMUSG00000121607,ENSG00000146938,ENSG00000165246,25.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
126,ENSMUSG00000144229,ENSG00000289282,ENSG00000288841,100.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN

,HumanID,MouseID,EuclidDist,EuclidDistNorm,EuclidDistLog,PearDist,TEC,Human +/-,Number of Human Exons,Human dN,Human dS,Human dN/dS,Mouse +/-,Number of Mouse Exons,Mouse dN,Mouse dS,Mouse dN/dS
0,ENSG00000000971,ENSMUSG00000000049,1648.502447,0.322558,9.334532,0.032440,0.250,NaN,<NA>,NaN,NaN,NaN,nan,16,0.1518,0.6863,0.22115
1,ENSG00000001036,ENSMUSG00000000056,71.067645,0.697079,3.998596,1.349007,0.000,nan,32,0.1007,0.6704,0.15014,nan,16,0.0844,0.6925,0.12193
2,ENSG00000001084,ENSMUSG00000000078,152.010822,0.680316,5.442806,0.618386,0.000,+,60,0.0288,0.5331,0.05394,nan,11,0.0237,0.6303,0.03765
3,ENSG00000001167,ENSMUSG00000000088,2119.855406,0.565457,16.948433,1.150569,0.000,-,73,0.0014,0.4015,0.00339,nan,11,0.0777,0.2894,0.26844
4,ENSG00000001561,ENSMUSG00000000094,28.852232,0.976974,8.429828,0.742289,0.375,nan,12,0.1056,0.5009,0.21082,-,13,0.0316,0.6066,0.05205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19733,ENSG00000300510,ENSMUSG00000109542,1.096681,NaN,1.230796,NaN,NaN,nan,10,0.2528,0.7142,0.35398,+,6,0.1593,0.4943,0.32230
19734,ENSG00000300510,ENSMUSG00000109542,1.096681,NaN,1.230796,NaN,NaN,nan,10,0.2112,1.6753,0.12610,+,6,0.1593,0.4943,0.32230
19735,ENSG00000300510,ENSMUSG00000109542,1.096681,NaN,1.230796,NaN,NaN,nan,10,0.2378,0.8741,0.27210,+,6,0.1593,0.4943,0.32230
19736,ENSG00000300510,ENSMUSG00000109542,1.096681,NaN,1.230796,NaN,NaN,nan,10,0.3612,1.1050,0.32691,+,6,0.1593,0.4943,0.32230
19737,ENSG00000310517,ENSMUSG00000109544,145.951064,NaN,14.834910,NaN,NaN,nan,213,0.1979,0.5928,0.33381,NaN,<NA>,NaN,NaN,NaN

In [3]:
headerCols = ["n", "Median", "Mean", "Rho", "Corr PValue"]
statsDF = pd.DataFrame(
    index = ["one-to-one", "one-to-many",
                "one-to-many, duplicated in human", 
                "one-to-many, duplicated in human, GOC=0", "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=100",
                "one-to-many, duplicated in mouse",
                "one-to-many, duplicated in mouse, GOC=0", "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=100",
                "many-to-many", "random",
                "trios, duplicated in human, parental", "trios, duplicated in human, daughter",
                "trios, duplicated in mouse, parental", "trios, duplicated in mouse, daughter"],
    columns=headerCols
)

In [4]:
sigDF = pd.DataFrame({
    "Group 1": ["one-to-one", "one-to-one",
                "one-to-many, duplicated in human",
                "many-to-many", "many-to-many",
                "one-to-many, duplicated in human, GOC=0", "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=0",
                "one-to-many, duplicated in mouse, GOC=0", "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=0",
                "trios, duplicated in human, parental", "trios, duplicated in mouse, parental"],

    "Group 2": ["one-to-many, duplicated in human", "one-to-many, duplicated in mouse",
                "one-to-many, duplicated in mouse", 
                "one-to-many, duplicated in human", "one-to-many, duplicated in mouse", 
                "one-to-many, duplicated in human, GOC=25", "one-to-many, duplicated in human, GOC=50", "one-to-many, duplicated in human, GOC=75", "one-to-many, duplicated in human, GOC=100", "one-to-many, duplicated in human, GOC=100",
                "one-to-many, duplicated in mouse, GOC=25", "one-to-many, duplicated in mouse, GOC=50", "one-to-many, duplicated in mouse, GOC=75", "one-to-many, duplicated in mouse, GOC=100", "one-to-many, duplicated in mouse, GOC=100",
                "trios, duplicated in human, daughter", "trios, duplicated in mouse, daughter"],
    "P-value": 0.0
})

In [5]:
translationTable = {
    "one-to-one": "ortholog_one2one",
    "one-to-many": "ortholog_one2many",
    "duplicated in human": "Human",
    "duplicated in mouse": "Mouse",
    "GOC=0": 0,
    "GOC=25": 25,
    "GOC=50": 50,
    "GOC=75": 75,
    "GOC=100": 100,
    "many-to-many": "ortholog_many2many",
    "random": "random",
    "trios": "ortholog_one2many",
    "duplicated in human": "Human",
    "duplicated in mouse": "Mouse",
    "parental": "Parent",
    "daughter": "Daughter"
}

In [6]:
randomGenesList = [randomGenesDF, randomGenesNoRetro, randomGenesNoOverUnderRepresentation]
dfValuesList = []
for idx, df in enumerate([orthoTable, orthoTableNoRetro, orthoTableNoOverUnderRepresentation]):
    dfValues = statsDF.to_dict(orient="index")
    for metric in df.columns[np.r_[4:9, 39:42]]:
        for category in statsDF.index:
            translatedCategory = list(map(translationTable.get, category.split(", ")))
            if "random" in translatedCategory:
                if metric not in df.columns[4:9]:
                    dfValues[category]["n"] = np.nan
                    dfValues[category]["Median"] = np.nan
                    dfValues[category]["Mean"] = np.nan
                    continue
                filteredDF = randomGenesList[idx]
            elif len(translatedCategory) == 1:
                filteredDF = df[df["Mouse homology type"] == translatedCategory[0]]
            elif len(translatedCategory) == 2:
                filteredDF = df[(df["Mouse homology type"] == translatedCategory[0]) & (df["Duplicated Species"] == translatedCategory[1])]
            elif len(translatedCategory) == 3 and isinstance(translatedCategory[2], int):
                filteredDF = df[(df["Mouse homology type"] == translatedCategory[0]) & (df["Duplicated Species"] == translatedCategory[1]) & (df["Mouse Gene-order conservation score"] == translatedCategory[2])]
            elif len(translatedCategory) == 3 and isinstance(translatedCategory[2], str):
                parentalDaughterDF = parentDaughterDFs[translatedCategory[1]][idx]
                filteredDF = parentalDaughterDF.filter(like=translatedCategory[2])
                filteredDF.columns = filteredDF.columns.str.replace(f" {translatedCategory[2]}", "")
            for column in statsDF.columns:
                if column == "n":
                    dfValues[category][column] = filteredDF[metric].dropna().shape[0]
                elif column == "Median":
                    dfValues[category][column] = filteredDF[metric].dropna().median()
                elif column == "Mean":
                    dfValues[category][column] = filteredDF[metric].dropna().mean()
                elif column == "Rho" and len(translatedCategory) > 1 and "one-to-many" in category:
                    filteredTissueNADF = filteredDF[(filteredDF[metric].notna()) & (filteredDF[f"Num {translatedCategory[1]} Dupes"].notna())]
                    dfValues[category][column] = stats.spearmanr(filteredTissueNADF[metric], filteredTissueNADF[f"Num {translatedCategory[1]} Dupes"]).statistic
                elif column == "Corr PValue" and len(translatedCategory) > 1 and "one-to-many" in category:
                    filteredTissueNADF = filteredDF[(filteredDF[metric].notna()) & (filteredDF[f"Num {translatedCategory[1]} Dupes"].notna())]
                    dfValues[category][column] = stats.spearmanr(filteredTissueNADF[metric], filteredTissueNADF[f"Num {translatedCategory[1]} Dupes"]).pvalue
        dfValuesList.append(pd.DataFrame(dfValues).T)

In [7]:
sigDFArr= []
for idx, df in enumerate([orthoTable, orthoTableNoRetro, orthoTableNoOverUnderRepresentation]):
    for metric in df.columns[np.r_[4:9, 39:42]]:
        pValueArr = []
        for rowNum in range(sigDF.shape[0]):
            translatedGroup1 = list(map(translationTable.get, sigDF.iloc[rowNum, :].iloc[0].split(", ")))
            translatedGroup2 = list(map(translationTable.get, sigDF.iloc[rowNum, :].iloc[1].split(", ")))
            if len(translatedGroup1) == 1:
                filteredDF1 = df[df["Mouse homology type"] == translatedGroup1[0]]
            elif len(translatedGroup1) == 2:
                filteredDF1 = df[(df["Mouse homology type"] == translatedGroup1[0]) & (df["Duplicated Species"] == translatedGroup1[1])]
            elif len(translatedGroup1) == 3 and isinstance(translatedGroup1[2], int):
                filteredDF1 = df[(df["Mouse homology type"] == translatedGroup1[0]) & (df["Duplicated Species"] == translatedGroup1[1]) & (df["Mouse Gene-order conservation score"] == translatedGroup1[2])]
            elif len(translatedGroup1) == 3 and isinstance(translatedGroup1[2], str):
                parentalDaughterDF1 = parentDaughterDFs[translatedGroup1[1]][idx]
                filteredDF1 = parentalDaughterDF1.filter(like=translatedGroup1[2])
                filteredDF1.columns = filteredDF1.columns.str.replace(f" {translatedGroup1[2]}", "")

            if len(translatedGroup2) == 1:
                filteredDF2 = df[df["Mouse homology type"] == translatedGroup2[0]]
            elif len(translatedGroup2) == 2:
                filteredDF2 = df[(df["Mouse homology type"] == translatedGroup2[0]) & (df["Duplicated Species"] == translatedGroup2[1])]
            elif len(translatedGroup2) == 3 and isinstance(translatedGroup2[2], int):
                filteredDF2 = df[(df["Mouse homology type"] == translatedGroup2[0]) & (df["Duplicated Species"] == translatedGroup2[1]) & (df["Mouse Gene-order conservation score"] == translatedGroup2[2])]
            elif len(translatedGroup2) == 3 and isinstance(translatedGroup2[2], str):
                parentalDaughterDF2 = parentDaughterDFs[translatedGroup2[1]][idx]
                filteredDF2 = parentalDaughterDF2.filter(like=translatedGroup2[2])
                filteredDF2.columns = filteredDF2.columns.str.replace(f" {translatedGroup2[2]}", "")

            pValueArr.append(stats.mannwhitneyu(filteredDF1[metric].dropna(), filteredDF2[metric].dropna())[1])

        sigDF["P-value"] = pValueArr
        sigDFArr.append(sigDF.copy())

In [ ]:
with pd.ExcelWriter("/Users/andrewhsu/Projects/McNair/data/analysisTable.xlsx") as w:
    for analysisTypeIdx in range(0, 3):
        for metricIdx, metric in enumerate(orthoTable.columns[np.r_[4:9, 39:42]]):
            if metric == "dN/dS":
                metric = "dNdS"
            if analysisTypeIdx == 0:
                dfValuesList[analysisTypeIdx * 5 + metricIdx].to_excel(w, sheet_name=metric, startrow=1, index=True)
                sigDFArr[analysisTypeIdx * 5 + metricIdx].to_excel(w, sheet_name=metric, startrow=1, startcol=8, index=False)
            else:
                dfValuesList[analysisTypeIdx * 5 + metricIdx].to_excel(w, sheet_name=metric, startrow=(21 * analysisTypeIdx + 3 + (analysisTypeIdx - 1)), index=True, header=False)
                sigDFArr[analysisTypeIdx * 5 + metricIdx].to_excel(w, sheet_name=metric, startrow=(21 * analysisTypeIdx + 3 + (analysisTypeIdx - 1)), startcol=8, index=False, header=False)

                sheet = w.sheets[metric]
                sheet.cell(row=24, column=1, value="Retrogenes Removed")
                sheet.cell(row=46, column=1, value="Under/Overrepresentation Removed")
                sheet.cell(row=1, column=1, value="Standard")
                sheet.cell(row=2, column=1, value="Category")